/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package udesc.br.vision;

import udesc.br.controller.CadastrarPacienteControlador;
import udesc.br.controller.ControladorPaineis;
import udesc.br.controller.ManterAgendaControlador;
import udesc.br.controller.ManterPacienteControlador;
import udesc.br.dao.ConsultaDAO;
import udesc.br.dao.PacienteDAO;
import udesc.br.repository.ConsultaRepositorio;
import udesc.br.repository.PacienteRepositorio;
import udesc.br.vision.consulta.ManterAgendaVisao;
import udesc.br.vision.components.TreeButton;
import udesc.br.vision.medicamentos.CadastrarMedicamentoVisao;
import udesc.br.vision.medicamentos.ManterMedicamentoVisao;
import udesc.br.vision.paciente.CadastrarPacienteVisao;
import udesc.br.vision.paciente.ManterPacienteVisao;

import java.awt.*;
import java.awt.event.ActionListener;

import udesc.br.controller.CadastrarMedicamentoControlador;
import udesc.br.controller.FinanceiroControlador;
import udesc.br.controller.ManterMedicamentoControlador;
import udesc.br.dao.MedicamentoDAO;
import udesc.br.dao.MovimentacaoFinanceiraDAO;
import udesc.br.repository.MedicamentoRepositorio;
import udesc.br.repository.MovimentacaoFinanceiraRepositorio;
import udesc.br.vision.financeiro.MovimentacaoFinanceiraVisao;

import javax.swing.*;

/**
 *
 * @author Andre
 */
public class FramePrincipalVisao extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FramePrincipalVisao.class.getName());
    private CardLayout layout;
    
    /**
     * Creates new form FramePrincipal
     */
    public FramePrincipalVisao() {
        initComponents();
        
        layout = (CardLayout) cardLayout.getLayout();
    }

    public void adicionarAcaoVoltar(ActionListener acao) {
        btnVoltar.addActionListener(acao);
    }

    public void adicionarAcaoAvancar(ActionListener acao) {
        vtnAvancar.addActionListener(acao);
    }

    public void adicionarAcaoRecarregar(ActionListener acao) {
        btnRecarregar.addActionListener(acao);
    }

    public void adicionarAcaoListarPacientes(ActionListener acao) {
        btnListarPacientes.addActionListener(acao);
    }

    public void adicionarAcaoListarMedicamentos(ActionListener acao) {
        btnListarMedicamentos.addActionListener(acao);
    }

    public void adicionarAcaoFinanceiro(ActionListener acao) {
        btnFinanceiro.addActionListener(acao);
    }

    public void adicionarAcaoCadastrarPaciente(ActionListener acao) {
        btnCadastrarPaciente.addActionListener(acao);
    }

    public void adicionarAcaoCadastrarMedicamento(ActionListener acao) {
        btnCadastrarMedicamento.addActionListener(acao);
    }

    public void adicionarAcaoAgenda(ActionListener acao) {
        btnAgenda.addActionListener(acao);
    }

    public JButton getBtnCadastrarMedicamento() {
        return btnCadastrarMedicamento;
    }

    public JButton getBtnListarMedicamentos() {
        return btnListarMedicamentos;
    }

    public JButton getBtnListarPacientes() {
        return btnListarPacientes;
    }

    public JButton getBtnMedicamentos() {
        return btnMedicamentos;
    }

    public JButton getBtnPacientes() {
        return btnPacientes;
    }

    public JButton getBtnCadastrarPaciente() {
        return btnCadastrarPaciente;
    }

    public void adicionarTela(JPanel tela, String titulo) {
        cardLayout.add(tela, titulo);

        cardLayout.revalidate();
        cardLayout.repaint();
    }

    public void mostrarTela(String nomeTela, ControladorPaineis controladorPaineis) {
        layout.show(cardLayout, nomeTela);
        controladorPaineis.atualizarTela();
    }

    public void adicionarComponente(JComponent componente) {
        this.add(componente);
        this.revalidate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnListarPacientes = new javax.swing.JButton();
        btnPacientes = new javax.swing.JButton();
        btnCadastrarPaciente = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnListarMedicamentos = new javax.swing.JButton();
        btnMedicamentos = new javax.swing.JButton();
        btnCadastrarMedicamento = new javax.swing.JButton();
        btnAgenda = new javax.swing.JButton();
        btnFinanceiro = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        vtnAvancar = new javax.swing.JButton();
        btnRecarregar = new javax.swing.JButton();
        cardLayout = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EasyMed");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnListarPacientes.setText("Editar e Excluir");
        btnListarPacientes.setMargin(new java.awt.Insets(2, 0, 3, 14));

        btnPacientes.setText("Pacientes");
        btnPacientes.setMargin(new java.awt.Insets(2, 0, 3, 14));

        btnCadastrarPaciente.setText("Cadastrar");
        btnCadastrarPaciente.setMargin(new java.awt.Insets(2, 0, 3, 14));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPacientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCadastrarPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(btnListarPacientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 0, 0))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCadastrarPaciente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnListarPacientes)
                .addGap(0, 0, 0))
        );

        btnListarMedicamentos.setText("Listar");
        btnListarMedicamentos.setMargin(new java.awt.Insets(2, 0, 3, 14));

        btnMedicamentos.setText("Medicamentos");
        btnMedicamentos.setMargin(new java.awt.Insets(2, 0, 3, 14));

        btnCadastrarMedicamento.setText("Cadastrar");
        btnCadastrarMedicamento.setMargin(new java.awt.Insets(2, 0, 3, 14));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMedicamentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCadastrarMedicamento, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(btnListarMedicamentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMedicamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCadastrarMedicamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnListarMedicamentos)
                .addGap(0, 0, 0))
        );

        btnAgenda.setText("Consultas");
        btnAgenda.setMargin(new java.awt.Insets(2, 0, 3, 14));

        btnFinanceiro.setText("Financeiro");
        btnFinanceiro.setMargin(new java.awt.Insets(2, 0, 3, 14));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/easyMed190.png"))); // NOI18N

        btnVoltar.setBackground(new java.awt.Color(249, 249, 249));
        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/arrow-left.png"))); // NOI18N
        btnVoltar.setBorder(null);

        vtnAvancar.setBackground(new java.awt.Color(249, 249, 249));
        vtnAvancar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/arrow-right.png"))); // NOI18N
        vtnAvancar.setBorder(null);
        vtnAvancar.addActionListener(this::vtnAvancarActionPerformed);

        btnRecarregar.setBackground(new java.awt.Color(249, 249, 249));
        btnRecarregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/reload.png"))); // NOI18N
        btnRecarregar.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(vtnAvancar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRecarregar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(logo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAgenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFinanceiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRecarregar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(vtnAvancar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFinanceiro, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cardLayout.setPreferredSize(new java.awt.Dimension(600, 0));
        cardLayout.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cardLayout, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cardLayout, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vtnAvancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vtnAvancarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vtnAvancarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgenda;
    private javax.swing.JButton btnCadastrarMedicamento;
    private javax.swing.JButton btnCadastrarPaciente;
    private javax.swing.JButton btnFinanceiro;
    private javax.swing.JButton btnListarMedicamentos;
    private javax.swing.JButton btnListarPacientes;
    private javax.swing.JButton btnMedicamentos;
    private javax.swing.JButton btnPacientes;
    private javax.swing.JButton btnRecarregar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JPanel cardLayout;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel logo;
    private javax.swing.JButton vtnAvancar;
    // End of variables declaration//GEN-END:variables
}
