/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package udesc.br.vision.medicamentos;

import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import udesc.br.exception.MedicamentoException;

/**
 *
 * @author andre
 */
public class CadastrarMedicamentoVisao extends javax.swing.JPanel {

    /**
     * Creates new form CadastrarMedicamentoVisa
     */
    public CadastrarMedicamentoVisao() {
        initComponents();
    }
    
    public void adicionarAcaoBtnCadastrar(ActionListener acao){
        btnSalvar.addActionListener(acao);
    }
    
    public String getMedicamentoNome() throws MedicamentoException{
        if (txtNome.getText().isEmpty())
            throw new MedicamentoException("Preencha o nome do Medicamento");
        return txtNome.getText();
    }
    public double getMedicamentoValorCompra() throws MedicamentoException{
         String valorString = txtValorCompra.getText().trim();
        
        try {
            return Double.parseDouble(valorString);
        } catch (NumberFormatException ex){
            throw new MedicamentoException("Formato do valor inválido");
        }
    }
        
    public double getMedicamentoEstoque() throws MedicamentoException{
         String estoqueString = txtEstoque.getText().trim();
        
        try {
            return Double.parseDouble(estoqueString);
        } catch (NumberFormatException ex){
            throw new MedicamentoException("Formato do estoque inválido");
        }
    }
    public void apresentarMensagem(String msg){
        JOptionPane.showMessageDialog(this.getParent(), msg);
    }
    public void limparTela(){
        txtEstoque.setText("");
        txtNome.setText("");
        txtValorCompra.setText("");
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalvar = new javax.swing.JButton();
        txtNome = new javax.swing.JTextField();
        txtValorCompra = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtEstoque = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(770, 300));

        btnSalvar.setText("Salvar Medicamento");

        jLabel1.setText("Nome");

        jLabel2.setText("Valor Compra");

        jLabel4.setText("Estoque (mg)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtEstoque)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1)
                        .addComponent(txtNome)
                        .addComponent(txtValorCompra)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addContainerGap(618, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtValorCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnSalvar)
                .addContainerGap(57, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtEstoque;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtValorCompra;
    // End of variables declaration//GEN-END:variables
}
